universe = vanilla
executable = /home/nishkal.rao/git_overlap/src/scripts/match_ml_population/gw_injections_non_spinning.py
accounting_group = ligo.sim.o3.cbc.pe.bilby
accounting_group_user = nishkal.rao
initialdir = /home/nishkal.rao/git_overlap/src/scripts/match_ml_population/
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
getenv = True 
arguments = $(ProcId)
log = /home/nishkal.rao/git_overlap/src/output/match_ml_population/condor/$(Process).log
output = /home/nishkal.rao/git_overlap/src/output/match_ml_population/condor/$(Process).out
error = /home/nishkal.rao/git_overlap/src/output/match_ml_population/condor/$(Process).err
Queue 100