universe = vanilla
executable = /home/nishkal.rao/git_overlap/src/scripts/match_ml_ecc_population/population_non_spinning_match_ecc(3D).py
accounting_group = ligo.sim.o3.cbc.pe.bilby
accounting_group_user = nishkal.rao
initialdir = /home/nishkal.rao/git_overlap/src/scripts/match_ml_ecc_population/
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
getenv = True
arguments = $(ProcId)
log = /home/nishkal.rao/git_overlap/src/output/match_ml_ecc_population/condor_match_ecc/$(Process).log
output = /home/nishkal.rao/git_overlap/src/output/match_ml_ecc_population/condor_match_ecc/$(Process).out
error = /home/nishkal.rao/git_overlap/src/output/match_ml_ecc_population/condor_match_ecc/$(Process).err
Queue 500 